### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EpQZzHSv&#x2F;30-a-team-implicit-flow-code-sample-chrome-extension"> A-Team &gt; Implicit Flow Code Sample &gt; Chrome Extension</a>

**Comment by Blackbaud-SteveBrush** [comment]
// Ideally, these endpoints would live in a microservice of their own.

[2:33]  
line 135, background.js. Is that applicable to this?

[2:37]  
Or this error message text?  Is your authorization microservice running? \n3) Did you start the authorization microservice in "Development" mode (type, `export ASPNETCORE_ENVIRONMENT=Development && dotnet run`)?'

**Comment by Blackbaud-ChristopherRodgers** [comment]
Code Review (CR) note: 
- Need to fill in "description" property in bower.json. Right now, the value is a palceholder: "## Purpose"
- I think it'd be nice to run our JS through JSLint to see if we're going against any best practices
  - e.g. We're using methods before they are defined (later in the script). Case statements aren't indented from Switch.
- Some of the comments in background.js are leftover from a previous tutorial and don't apply to this one
- There seems to be a caching issue where the extension won't load the consent form the first time the page is visited. We've talked about this already--you're already looking at it.
  - I also noticed the same behavior if I sat on the page a while. I'm not sure the 401--unauthorized--check in order to check if we need to re-consent is working like it should.

**Comment by Blackbaud-SteveBrush** [comment]
Thanks, @Blackbaud-ChristopherRodgers !

**Pull request merged**
